### ISSUE TITLE
Migrate from glue.ligolw to python-ligo-lw

### ISSUE THREAD

**Issue by duncanmmacleod** [oshaughn/research-projects-RIT#64]
The LIGO_LW XML I/O library in `glue.ligolw` is deprecated, please migrate RIFTs XML I/O to use the new python-ligo-lw library.

In the simplest possible case this should only require search/replace `glue.ligolw` -> `ligo.lw`.

**Comment by oshaughn** [comment]
We can do this, however we are extremely wary that this breaks backward compatibility of XML (i.e., ilwdchar-compat)

**Comment by oshaughn** [comment]
Giving it a try in the development branch now (temp-RIT-Tides-port_python3_restructure_package)

**Comment by duncanmmacleod** [comment]
`glue.ligolw` ***will*** be removed at some point in the not-too-distant-future, so this will be forced upon you before long.

**Comment by oshaughn** [comment]
This is done on our core codebase, though a handful of relic/rarely used investigation tools have not yet been updated.  Closing for now.
